[build]
  command = "npm run build:production"
  publish = "apps/marketing/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--omit=dev"

# Skip installing browser dependencies in production
[build.processing]
  skip_processing = false

# Redirect all paths to the Astro app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200




