# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = [
  "rm -rf node_modules/.cache || true",
  "npm install --omit=dev --cache /tmp/.npm --prefer-offline --no-audit --no-fund",
  "cd apps/marketing && rm -rf node_modules/.cache || true",
  "cd apps/marketing && npm install --omit=dev --cache /tmp/.npm --prefer-offline --no-audit --no-fund", 
  "cd apps/marketing && npm run prebuild",
  "cd apps/marketing && npm run build"
]

[phases.start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT"
