[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "npm install",
  "cd apps/marketing && npm install"
]

[phases.build]
cmds = [
  "cd apps/marketing && npm run prebuild",
  "cd apps/marketing && npm run build"
]

[start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT"
