[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install", "cd apps/marketing && npm install"]

[phases.build]
cmds = ["npm run build:production"]

[start]
cmd = "cd apps/marketing && npx serve dist -s -n -L -p $PORT"
