[variables]
NODE_ENV = "production"
NPM_CONFIG_PLATFORM = "linux"
NPM_CONFIG_TARGET_PLATFORM = "linux"

[phases.install]
cmds = [
  "npm install --platform=linux --target-platform=linux",
  "cd apps/marketing && npm install --platform=linux --target-platform=linux"
]

[phases.build]
cmds = [
  "cd apps/marketing && npm run prebuild",
  "cd apps/marketing && npm run build"
]

[start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT"
