[variables]
NODE_ENV = "production"

[phases.install]
cmds = [
  "npm ci --include=dev",
  "cd apps/marketing && npm ci --include=dev"
]

[phases.build]
cmds = ["npm run build:production"]

[start]
cmd = "cd apps/marketing && npx serve dist -s -n -L -p $PORT"
