# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = [
  "npm config set cache /tmp/.npm",
  "npm config set fund false", 
  "npm config set audit false",
  "find . -name 'package-lock.json' -delete || true",
  "find . -name 'node_modules' -type d -exec rm -rf {} + 2>/dev/null || true",
  "npm install --force",
  "cd apps/marketing && npm install --force",
  "cd apps/marketing && npm run prebuild",
  "cd apps/marketing && npm run build"
]

[phases.start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT --allowed-hosts all"
