[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:production"]

[start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT"
