# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = [
  "npm ci --cache /tmp/.npm --prefer-offline --no-audit",
  "cd apps/marketing && npm ci --cache /tmp/.npm --prefer-offline --no-audit", 
  "cd apps/marketing && npm run prebuild",
  "cd apps/marketing && npm run build"
]

[phases.start]
cmd = "cd apps/marketing && npm run preview -- --host 0.0.0.0 --port $PORT"
